#! /bin/bash


python getEnergyEvents.py -a 0 -t proton
python getEnergyEvents.py -a 1 -t proton
python getEnergyEvents.py -a 2 -t proton
python getEnergyEvents.py -a 3 -t proton
python getEnergyEvents.py -a 4 -t proton
python getEnergyEvents.py -a 5 -t proton
python getEnergyEvents.py -a 6 -t proton
python getEnergyEvents.py -a 7 -t proton
python getEnergyEvents.py -a 8 -t proton
python getEnergyEvents.py -a 9 -t proton
python getEnergyEvents.py -a 10 -t proton
python getEnergyEvents.py -a 11 -t proton
python getEnergyEvents.py -a 12 -t proton
python getEnergyEvents.py -a 13 -t proton
python getEnergyEvents.py -a 14 -t proton
python getEnergyEvents.py -a 15 -t proton
python getEnergyEvents.py -a 16 -t proton
python getEnergyEvents.py -a 17 -t proton
python getEnergyEvents.py -a 18 -t proton
python getEnergyEvents.py -a 19 -t proton
python getEnergyEvents.py -a 20 -t proton
python getEnergyEvents.py -a 21 -t proton
python getEnergyEvents.py -a 22 -t proton
python getEnergyEvents.py -a 23 -t proton
python getEnergyEvents.py -a 24 -t proton
python getEnergyEvents.py -a 25 -t proton
python getEnergyEvents.py -a 26 -t proton
python getEnergyEvents.py -a 27 -t proton
python getEnergyEvents.py -a 28 -t proton
python getEnergyEvents.py -a 29 -t proton
python getEnergyEvents.py -a 30 -t proton
python getEnergyEvents.py -a 31 -t proton
python getEnergyEvents.py -a 32 -t proton
python getEnergyEvents.py -a 33 -t proton
python getEnergyEvents.py -a 34 -t proton
python getEnergyEvents.py -a 35 -t proton
python getEnergyEvents.py -a 36 -t proton
python getEnergyEvents.py -a 37 -t proton

python getEnergyEvents.py -a 0 -t iron
python getEnergyEvents.py -a 1 -t iron
python getEnergyEvents.py -a 2 -t iron
python getEnergyEvents.py -a 3 -t iron
python getEnergyEvents.py -a 4 -t iron
python getEnergyEvents.py -a 5 -t iron
python getEnergyEvents.py -a 6 -t iron
python getEnergyEvents.py -a 7 -t iron
python getEnergyEvents.py -a 8 -t iron
python getEnergyEvents.py -a 9 -t iron
python getEnergyEvents.py -a 10 -t iron
python getEnergyEvents.py -a 11 -t iron
python getEnergyEvents.py -a 12 -t iron
python getEnergyEvents.py -a 13 -t iron
python getEnergyEvents.py -a 14 -t iron
python getEnergyEvents.py -a 15 -t iron
python getEnergyEvents.py -a 16 -t iron
python getEnergyEvents.py -a 17 -t iron
python getEnergyEvents.py -a 18 -t iron
python getEnergyEvents.py -a 19 -t iron
python getEnergyEvents.py -a 20 -t iron
python getEnergyEvents.py -a 21 -t iron
python getEnergyEvents.py -a 22 -t iron
python getEnergyEvents.py -a 23 -t iron
